// <auto-generated />
using System;
using FastFoodWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FastFoodWeb.Migrations
{
    [DbContext(typeof(FastFoodDbContext))]
    partial class FastFoodDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.36")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("FastFoodWeb.Models.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Burgery"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Napoje"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Dodatki"
                        });
                });

            modelBuilder.Entity("FastFoodWeb.Models.OrderItems", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<int?>("OrdersId")
                        .HasColumnType("int");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(65,30)");

                    b.Property<int>("Quantity")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.HasIndex("OrdersId");

                    b.ToTable("OrderItems");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 1,
                            Name = "Hamburger",
                            Price = 10.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 1,
                            Name = "Cheeseburger",
                            Price = 12.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 1,
                            Name = "Kurczakburger",
                            Price = 12.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 2,
                            Name = "Cola",
                            Price = 3.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 5,
                            CategoryId = 2,
                            Name = "Fanta",
                            Price = 4.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 6,
                            CategoryId = 2,
                            Name = "Lipton",
                            Price = 4.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 7,
                            CategoryId = 3,
                            Name = "Frytki małe",
                            Price = 5.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 8,
                            CategoryId = 3,
                            Name = "Frytki duże",
                            Price = 6.99m,
                            Quantity = 0
                        },
                        new
                        {
                            Id = 9,
                            CategoryId = 3,
                            Name = "Sałatka",
                            Price = 7.99m,
                            Quantity = 0
                        });
                });

            modelBuilder.Entity("FastFoodWeb.Models.Orders", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<bool>("Completed")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("OrderDate")
                        .HasColumnType("datetime(6)");

                    b.Property<decimal>("TotalAmount")
                        .HasColumnType("decimal(65,30)");

                    b.HasKey("Id");

                    b.ToTable("Orders");
                });

            modelBuilder.Entity("FastFoodWeb.Models.OrderItems", b =>
                {
                    b.HasOne("FastFoodWeb.Models.Category", "Category")
                        .WithMany("Items")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FastFoodWeb.Models.Orders", "Orders")
                        .WithMany("Items")
                        .HasForeignKey("OrdersId");

                    b.Navigation("Category");

                    b.Navigation("Orders");
                });

            modelBuilder.Entity("FastFoodWeb.Models.Category", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("FastFoodWeb.Models.Orders", b =>
                {
                    b.Navigation("Items");
                });
#pragma warning restore 612, 618
        }
    }
}
